[package]
name = "neutron"
edition.workspace = true
version.workspace = true

[dependencies]
base = { path = "../base" }
db = { path = "../db" }
layout = { path = "../layout" }
session = { path = "../session" }

dirs = "7"
masonry = "0.4"
masonry_winit = "0.4"
tokio = { version = "1", features = ["time"] }
xilem = "0.4"

[dev-dependencies]
ttf-parser = "0.25"
